V0.7
lukaszmazurkiewicz/tictactoe pull request #6
Opened 2018-11-23 22:03 UTC by lukaszmazurkiewicz

2018-11-24 15:31 UTC, MARudnicki requested changes

2018-11-24 15:31 UTC, MARudnicki commented on src/main/test/ticktacktoe/GameTest.java
> +        zeroingScore();
problem wynika z tego ze `zeroingScore` w tescie wskazuje NIE na zeroingScore w game, tylko na metode testową. Tzwn. zeroingScore woła sama siebie w klasie GameTest

2018-11-24 15:31 UTC, MARudnicki commented on src/main/test/ticktacktoe/GameTest.java
> +        zeroingScore();
Niestety po poprawie tego na `game.zeroingScore()` i tak dostaniesz blad 
wynikajacy z tego ze `new HBox(playerOneName, playerOneScore, playerTwoName, playerTwoScore)` przyjmuje playerOneName i playerTwoName rowne null. 
Jest mozliwe napisanie testow do UI (czyli do wygladu, planszy itd w javafx), ale jest do dosc trudne
https://medium.com/information-and-technology/test-driven-development-in-javafx-with-testfx-66a84cd561e0

2018-11-26 08:04 UTC, MARudnicki requested changes

2018-11-26 08:04 UTC, MARudnicki commented on src/main/java/ticktacktoe/SavingGame.java
> +    }
Zrobilem kilka zmian i dziala bez problemu
```
public class SavingService {

    private static final String GAME_STATE_PATH = "SavedGames.txt";
    Map<String, String> results = new HashMap<>();

    public void saveMap() {
        try {
            System.out.println("Saving game");
            File file = new File(GAME_STATE_PATH);
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file));
            oos.writeObject(results);
            oos.close();
        } catch (Exception e) {
            System.out.println("Exception occurred " + e.getMessage());
        }
        System.out.println("Game saved");
    }

    public void loadMap() {
        try {
            File file = new File(GAME_STATE_PATH);
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));
            Object readMap = ois.readObject();
            if (readMap instanceof HashMap) {
                results.putAll((HashMap) readMap);
            }
            ois.close();
            System.out.println("Loaded results " + results);
        } catch (Exception e) {

        }
    }
}
```

2018-11-26 08:04 UTC, MARudnicki commented on src/main/java/ticktacktoe/SavingGame.java
> +    }
+ przemianowanie na SavingService

2018-11-26 12:40 UTC, lukaszmazurkiewicz commented on src/main/java/ticktacktoe/SavingGame.java
> +    }
save.results.put(playerName,Integer.toString(user.getUserScore()) + "|" + Integer.toString(user.getCompScore()) + "|" + Integer.toString(numberOfRounds));
            save.saveMap();

a czy taki sposób zapisu jest poprawny? bo generalnie wszystko działa już teraz rzeczywiście ale w sumie w  tym pliku savedgames.txt nic się nie zapisuje

2018-11-27 17:33 UTC, merged